
import { Resource } from "./types";

export const allResources: Resource[] = [
  {
    id: "res001",
    title: "Manual de seguridad en operaciones mineras",
    description: "Guía completa con protocolos de seguridad para operaciones mineras según estándares internacionales",
    type: "document",
    category: "safety",
    fileType: "PDF",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "8.2 MB",
    createdAt: "2025-03-15",
    updatedAt: "2025-03-15",
    author: "Departamento de Seguridad",
    featured: true,
    downloadCount: 1245,
    isFavorite: false
  },
  {
    id: "res002",
    title: "Procedimientos de excavación subterránea",
    description: "Manual técnico con metodologías y mejores prácticas para excavaciones subterráneas",
    type: "document",
    category: "mining",
    fileType: "PDF",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "12.5 MB",
    createdAt: "2025-02-20",
    updatedAt: "2025-03-10",
    author: "Instituto de Minería Subterránea",
    featured: false,
    downloadCount: 876,
    isFavorite: true
  },
  {
    id: "res003",
    title: "Tutorial: Análisis de muestras metalúrgicas",
    description: "Video tutorial que explica el proceso de análisis de muestras en laboratorio metalúrgico",
    type: "video",
    category: "engineering",
    thumbnail: "https://github.com/shadcn.png",
    url: "https://example.com/video/metalurgia",
    createdAt: "2025-01-28",
    updatedAt: "2025-01-28",
    author: "Dr. Roberto Méndez",
    featured: false,
    downloadCount: 560,
    isFavorite: false
  },
  {
    id: "res004",
    title: "Plantilla para evaluación de impacto ambiental",
    description: "Documento plantilla para realizar estudios de impacto ambiental en proyectos mineros",
    type: "template",
    category: "environment",
    fileType: "DOCX",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "2.8 MB",
    createdAt: "2025-03-05",
    updatedAt: "2025-03-05",
    author: "División de Sostenibilidad",
    featured: false,
    downloadCount: 423,
    isFavorite: true
  },
  {
    id: "res005",
    title: "Software para diseño de tajo abierto (versión educativa)",
    description: "Herramienta especializada para diseño y planificación de minas a cielo abierto",
    type: "software",
    category: "engineering",
    thumbnail: "https://github.com/shadcn.png",
    url: "https://example.com/software/tajo-abierto",
    createdAt: "2024-11-15",
    updatedAt: "2025-02-10",
    author: "MineTech Solutions",
    featured: true,
    downloadCount: 789,
    isFavorite: false
  },
  {
    id: "res006",
    title: "Tutorial: Gestión de equipos multidisciplinarios",
    description: "Serie de videos sobre liderazgo y gestión de equipos en proyectos mineros",
    type: "tutorial",
    category: "management",
    thumbnail: "https://github.com/shadcn.png",
    url: "https://example.com/tutorial/liderazgo",
    createdAt: "2025-01-20",
    updatedAt: "2025-01-20",
    author: "Dra. Carla Vega",
    featured: false,
    downloadCount: 312,
    isFavorite: false
  },
  {
    id: "res007",
    title: "Informe: Tendencias en minería sostenible",
    description: "Análisis de las últimas tendencias en sostenibilidad para la industria minera global",
    type: "document",
    category: "environment",
    fileType: "PDF",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "5.4 MB",
    createdAt: "2025-04-02",
    updatedAt: "2025-04-02",
    author: "Fundación Minería Sostenible",
    featured: true,
    downloadCount: 645,
    isFavorite: false
  },
  {
    id: "res008",
    title: "Plantillas para reportes de producción",
    description: "Conjunto de plantillas para seguimiento y reporte de indicadores de producción minera",
    type: "template",
    category: "management",
    fileType: "XLSX",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "1.8 MB",
    createdAt: "2025-03-18",
    updatedAt: "2025-03-18",
    author: "Departamento de Operaciones",
    featured: false,
    downloadCount: 520,
    isFavorite: true
  },
  {
    id: "res009",
    title: "Innovación en procesos hidrometalúrgicos",
    description: "Artículo técnico sobre avances recientes en procesos hidrometalúrgicos",
    type: "article",
    category: "engineering",
    fileType: "PDF",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "3.2 MB",
    createdAt: "2025-02-28",
    updatedAt: "2025-02-28",
    author: "Revista Ingeniería Metalúrgica",
    featured: false,
    downloadCount: 234,
    isFavorite: false
  },
  {
    id: "res010",
    title: "Curso completo: Geomecánica aplicada",
    description: "Material completo del curso con presentaciones, ejercicios y soluciones",
    type: "tutorial",
    category: "mining",
    fileType: "ZIP",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "45.7 MB",
    createdAt: "2025-01-10",
    updatedAt: "2025-01-10",
    author: "Prof. Andrés Torres",
    featured: false,
    downloadCount: 187,
    isFavorite: false
  },
  {
    id: "res011",
    title: "Guía de cumplimiento normativo",
    description: "Manual para asegurar el cumplimiento de regulaciones mineras nacionales e internacionales",
    type: "document",
    category: "general",
    fileType: "PDF",
    thumbnail: "https://github.com/shadcn.png",
    fileSize: "9.3 MB",
    createdAt: "2025-03-25",
    updatedAt: "2025-03-25",
    author: "Departamento Legal",
    featured: false,
    downloadCount: 430,
    isFavorite: false
  },
  {
    id: "res012",
    title: "Tutorial: Uso de software de ventilación minera",
    description: "Video tutorial sobre el uso de software especializado para diseño de sistemas de ventilación",
    type: "video",
    category: "safety",
    thumbnail: "https://github.com/shadcn.png",
    url: "https://example.com/video/ventilacion",
    createdAt: "2025-02-15",
    updatedAt: "2025-02-15",
    author: "Ing. Patricia Sánchez",
    featured: false,
    downloadCount: 276,
    isFavorite: false
  }
];
