// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnjxbvghntwwrvqqqdvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuanhidmdobnR3d3J2cXFxZHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjA5ODUsImV4cCI6MjA1ODE5Njk4NX0.ld_GhzTgOicboiyBnAZ8G54RtBd0XLfGtkPGNHxKg34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);