
import { Assessment } from "./types";

export const allAssessments: Assessment[] = [
  {
    id: "as001",
    title: "Fundamentos del Trading Forex",
    description: "Evaluación de conocimientos básicos sobre el mercado de divisas, pares de monedas y análisis fundamental",
    category: "forex",
    type: "practice",
    level: "Principiante",
    duration: 30,
    questionsCount: 20,
    requiresPrevious: false,
    popularity: "Popular",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as002", 
    title: "Análisis Técnico Avanzado",
    description: "Prueba tus conocimientos sobre indicadores técnicos, patrones de gráficos y estrategias de trading",
    category: "forex",
    type: "practice", 
    level: "Intermedio",
    duration: 45,
    questionsCount: 30,
    requiresPrevious: false,
    popularity: "Destacado",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as003",
    title: "Gestión de Riesgo en Trading",
    description: "Evaluación sobre técnicas de gestión de capital, stop loss, take profit y psicología del trading",
    category: "forex",
    type: "practice",
    level: "Avanzado", 
    duration: 60,
    questionsCount: 35,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as004",
    title: "Trading de Criptomonedas",
    description: "Evalúa tu comprensión sobre Bitcoin, Ethereum, análisis on-chain y trading de altcoins",
    category: "crypto",
    type: "practice",
    level: "Intermedio",
    duration: 40,
    questionsCount: 25,
    requiresPrevious: false,
    popularity: "Nuevo",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as005",
    title: "Certificación Profesional en Forex",
    description: "Evaluación oficial para obtener la certificación profesional en trading de divisas",
    category: "forex",
    type: "certification",
    level: "Profesional", 
    duration: 120,
    questionsCount: 50,
    requiresPrevious: true,
    popularity: "Destacado",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as006",
    title: "Certificación en Trading de Acciones",
    description: "Evaluación completa para certificar competencias en análisis fundamental y trading de acciones",
    category: "stocks",
    type: "certification",
    level: "Profesional",
    duration: 150,
    questionsCount: 60,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as007",
    title: "Especialista en Trading Algorítmico",
    description: "Certificación especializada para traders que utilizan algoritmos y trading automatizado",
    category: "stocks",
    type: "certification", 
    level: "Especialista",
    duration: 180,
    questionsCount: 45,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as008",
    title: "Certificación en DeFi y Trading Descentralizado",
    description: "Evaluación para certificar conocimientos en finanzas descentralizadas y protocolos DeFi",
    category: "crypto",
    type: "certification",
    level: "Profesional",
    duration: 100,
    questionsCount: 40,
    requiresPrevious: true,
    popularity: "Nuevo",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as009",
    title: "Evaluación de Habilidades en Scalping",
    description: "Comprueba tus habilidades técnicas para el trading a corto plazo y scalping",
    category: "forex",
    type: "skill-check",
    level: "Intermedio",
    duration: 45,
    questionsCount: 15,
    requiresPrevious: false,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as010",
    title: "Análisis de Casos de Trading Real",
    description: "Test de habilidades para evaluar y resolver situaciones reales de trading en mercados volátiles",
    category: "forex",
    type: "skill-check",
    level: "Avanzado",
    duration: 60,
    questionsCount: 12,
    requiresPrevious: false,
    popularity: "Popular",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as011",
    title: "Resolución de Problemas en Trading Cuantitativo",
    description: "Evaluación práctica para resolver situaciones complejas usando modelos matemáticos",
    category: "stocks",
    type: "skill-check",
    level: "Experto",
    duration: 90,
    questionsCount: 8,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as012",
    title: "Liderazgo en Equipos de Trading",
    description: "Evaluación de competencias para liderar equipos de trading en fondos de inversión",
    category: "stocks",
    type: "skill-check",
    level: "Avanzado",
    duration: 75,
    questionsCount: 12,
    requiresPrevious: false,
    popularity: "Nuevo",
    image: "https://github.com/shadcn.png"
  }
];
