
import { Assessment } from "./types";

export const allAssessments: Assessment[] = [
  {
    id: "as001",
    title: "Fundamentos de seguridad minera",
    description: "Evaluación de conocimientos sobre principios fundamentales de seguridad en operaciones mineras",
    category: "mining",
    type: "practice",
    level: "Principiante",
    duration: 45,
    questionsCount: 25,
    requiresPrevious: false,
    popularity: "Popular",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as002",
    title: "Normativa de medio ambiente en minería",
    description: "Prueba tus conocimientos sobre regulaciones y normativas ambientales aplicadas a la industria minera",
    category: "mining",
    type: "practice",
    level: "Intermedio",
    duration: 60,
    questionsCount: 30,
    requiresPrevious: false,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as003",
    title: "Gestión de proyectos mineros",
    description: "Evaluación práctica sobre metodologías y técnicas de gestión aplicadas a proyectos mineros",
    category: "management",
    type: "practice",
    level: "Avanzado",
    duration: 75,
    questionsCount: 35,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as004",
    title: "Procesos metalúrgicos",
    description: "Evalúa tu comprensión sobre los principales procesos metalúrgicos utilizados en la industria",
    category: "engineering",
    type: "practice",
    level: "Intermedio",
    duration: 60,
    questionsCount: 30,
    requiresPrevious: false,
    popularity: "Destacado",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as005",
    title: "Certificación Profesional en Seguridad Minera",
    description: "Evaluación oficial para obtener la certificación profesional en seguridad para operaciones mineras",
    category: "mining",
    type: "certification",
    level: "Profesional",
    duration: 120,
    questionsCount: 50,
    requiresPrevious: true,
    popularity: "Destacado",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as006",
    title: "Certificación en Gestión de Proyectos Mineros",
    description: "Evaluación completa para certificar competencias en dirección y gestión de proyectos mineros",
    category: "management",
    type: "certification",
    level: "Profesional",
    duration: 180,
    questionsCount: 60,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as007",
    title: "Validación de competencias en metalurgia extractiva",
    description: "Certificación especializada para profesionales en metalurgia enfocada en extracción mineral",
    category: "engineering",
    type: "certification",
    level: "Especialista",
    duration: 150,
    questionsCount: 55,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as008",
    title: "Certificación en Sostenibilidad para la Minería",
    description: "Evaluación para certificar conocimientos en prácticas sostenibles y responsabilidad social corporativa",
    category: "mining",
    type: "certification",
    level: "Profesional",
    duration: 120,
    questionsCount: 50,
    requiresPrevious: true,
    popularity: "Nuevo",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as009",
    title: "Evaluación de habilidades en diseño de minas",
    description: "Comprueba tus habilidades técnicas para el diseño de operaciones mineras",
    category: "engineering",
    type: "skill-check",
    level: "Intermedio",
    duration: 90,
    questionsCount: 15,
    requiresPrevious: false,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as010",
    title: "Análisis de casos de seguridad minera",
    description: "Test de habilidades para evaluar y resolver situaciones críticas de seguridad en minería",
    category: "mining",
    type: "skill-check",
    level: "Avanzado",
    duration: 60,
    questionsCount: 10,
    requiresPrevious: false,
    popularity: "Popular",
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as011",
    title: "Resolución de problemas en procesos metalúrgicos",
    description: "Evaluación práctica para resolver situaciones complejas en procesos metalúrgicos",
    category: "engineering",
    type: "skill-check",
    level: "Experto",
    duration: 120,
    questionsCount: 8,
    requiresPrevious: true,
    popularity: null,
    image: "https://github.com/shadcn.png"
  },
  {
    id: "as012",
    title: "Liderazgo de equipos en proyectos mineros",
    description: "Evaluación de competencias para liderar equipos multidisciplinarios en proyectos del sector",
    category: "management",
    type: "skill-check",
    level: "Avanzado",
    duration: 75,
    questionsCount: 12,
    requiresPrevious: false,
    popularity: "Nuevo",
    image: "https://github.com/shadcn.png"
  }
];
